### ISSUE TITLE
Version 3 does not work in Rails 7

### ISSUE THREAD

**Issue by gstokkink** [danielfone/as_csv#12] opened 2023-01-26 10:36 UTC
Hi,

First of all, thanks for your work on this gem!

I have noticed that since version 3, the gem is no longer loaded correctly for Rails 7 at least. I had to downgrade to 2.0.2 to have access to the `as_csv` method on my records. Looks like the railtie is not functioning correctly?

**Comment by danielfone** [comment] 2023-01-27 09:51
Hi @gstokkink! I'm surprised to hear you're having an issue with Rails 7. Version 3 is intended to support Rails 7 and it is tested with it. Can you give some more details so I can try to reproduce the issue?

**Comment by gstokkink** [comment] 2023-01-27 12:48
I basically upgrade my application to Rails 7 and the gem to version 3, and the `as_csv` method was no longer defined for any ActiveRecord instance.

**Comment by danielfone** [comment] 2023-01-30 20:41
@gstokkink which version of Ruby are you using, and which specific version of Rails? I'll see if I can reproduce.

**Comment by danielfone** [comment] 2023-02-01 03:26
@gstokkink, thanks. Can you try the `improve-railtie` branch locally to see if it fixes it? If so, I'll tidy it up and release a new version. I'm actually inclined to release a new major version that does away with the monkey patching entirely — it's a bit fragile.

**Comment by gstokkink** [comment] 2023-02-01 08:08
@danielfone that seems to work! I can call `to_csv` on AR objects and relations.

**Comment by danielfone** [comment] 2023-02-01 09:09
@gstokkink I've just released v3.0.1. I'm closing this issue, but feel free to reopen if anything is amiss!

**Closed by danielfone** 2023-02-01 09:09 UTC
